min_sensor_dist: .05

# The default padding to be added for the body parts the robot can see
self_see_default_padding: .04

# The default scaling to be added for the body parts the robot can see
self_see_default_scale: 1.0

self_see_links:
  - name: katana_internal_controlbox_link 
  - name: katana_base_link
  - name: katana_motor1_pan_link
  - name: katana_motor2_lift_link
    padding: 0.06
  - name: katana_motor3_lift_link
    padding: 0.06
  - name: katana_motor4_lift_link
    padding: 0.06
  - name: katana_motor5_wrist_roll_link
    padding: 0.03
  - name: katana_gripper_link
    padding: 0.03
  - name: katana_l_finger_link
    padding: 0.02
  - name: katana_r_finger_link
    padding: 0.02
  
